### ISSUE TITLE
Repo Link

### ISSUE THREAD

**Issue by gargi** [SoftwareEngineeringToolDemos/ICSE-2011-Covana#6]
The GitHub repository page should have a link to the original website after the description at the top.

**Comment by smalleni** [comment]
Project website: http://research.csc.ncsu.edu/ase/projects/covana/

Present in the readme given by the authors themselves, I just appended remaining things below.

**Comment by gargi** [comment]
It should be present on the top according to this:
At the top of the page, is a project website filled in with a link to the original website? [link]
