### ISSUE TITLE
Inconsistency with repository format

### ISSUE THREAD

**Issue by gargi** [SoftwareEngineeringToolDemos/ICSE-2011-Covana#7]
Considering consistency with other repositories, should the project summary, installation etc be present before all the information such as paper link, video and all the Readme requirements?

**Comment by smalleni** [comment]
I thought professor said if there was already an existing readme we just append to it, right?

**Comment by gargi** [comment]
Hi,
Sorry I was unaware of this. I am closing this issue.

**Comment by smalleni** [comment]
No problem, thanks for checking though
